name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libopencv-dev python3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake .. -DBUILD_PYTHON_BINDINGS=ON
    
    - name: Build
      run: |
        cd build
        make
    
    - name: Install
      run: |
        cd build
        sudo make install
    
    - name: Test Python Module
      run: |
        python -c "import lpximage; print('Module successfully imported!')"

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        brew install cmake opencv
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake .. -DBUILD_PYTHON_BINDINGS=ON -DPython_EXECUTABLE=$(which python) -DCMAKE_INSTALL_RPATH="/usr/local/lib" -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON -DCMAKE_MACOSX_RPATH=ON
    
    - name: Build
      run: |
        cd build
        make
    
    - name: Install
      run: |
        cd build
        sudo make install
    
    - name: Test Python Module
      run: |
        python -c "import lpximage; print('Module successfully imported!')"

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install opencv-python
    
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DBUILD_PYTHON_BINDINGS=ON
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Release
    
    - name: Install
      run: |
        cd build
        cmake --install . --config Release
    
    - name: Test Python Module
      run: |
        python -c "import lpximage; print('Module successfully imported!')"
