name: Cross-Platform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16.x, 18.x, 20.x]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    # Install node-gyp globally
    - name: Install node-gyp
      run: npm install -g node-gyp
      
    # Platform-specific setup for C++ tools
    - name: Setup Linux C++ environment
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ python3
        
    - name: Setup macOS C++ environment
      if: runner.os == 'macOS'
      run: |
        xcode-select --install || true
        
    - name: Setup Windows C++ environment
      if: runner.os == 'Windows'
      run: |
        npm install --global windows-build-tools || true
        
    # Install dependencies
    - name: Install dependencies
      run: npm ci
      
    # Build C++ components
    - name: Build C++ components
      run: npm run build
      
    # Run tests
    - name: Run tests
      run: npm test